refactor(./internal/server): sprint1 iter3 gin router setup
avtorsky/cuttlink pull request #3
Opened 2022-12-26 13:28 UTC by avtorsky

2022-12-27 12:56 UTC, Barugoo commented on internal/server/server.go
> +		url = strings.TrimSuffix(string(urlBytes), "\n")
Там может же быть произвольное количество `\n` и пробелов. Лучше использовать `strings.TrimSpace` для таких случаев

2022-12-27 12:56 UTC, Barugoo commented on internal/server/server.go
> +		}
Круто, что ты сделал ручку для веб-морды, но давай разнесем эти кейсы по отдельным хэндлерам - один будет обслуживать инпут из хтмл формы, другой body с plain-текстом

2022-12-27 12:58 UTC, Barugoo commented on internal/server/server.go
> +	if url == "" {
А если она непустая, но нам передали не урл а рандомную строку? Давай тогда еще `url.Parse` попробуем применить к `url`, если ошибка не пустая вернется, значит url невалидный и мы возвращаем 400

2022-12-27 13:21 UTC, Barugoo commented on internal/services/services.go
> +}
А зачем на оно? Давай уберем
И почему в одном методе мы называем сущность `Link` а в другом `Redirect`? Давай оставим `Link` или `ShortURL`

2022-12-27 13:29 UTC, Barugoo commented on internal/services/services.go
> +}
Не совсем понимаю, зачем у нас обернуто локальное хранилище в собственный интерфейс. Мне не кажется, что нам потребуется поддерживать несколько разных реализаций хранилищ в памяти. Давай сделаем общий интерфейс `Storage` и там опишем методы с привязкой к конкретным сущностям (потому что сейчас у тебя выглядит интерфейс так, будто он не привязывается ни к чему, а внутри реализации методов при этом ты называешь параметры `url`, а мапку - `links`) и возвратом ошибок из каждого метода.

2022-12-27 13:31 UTC, Barugoo requested changes
Хорошо, но есть замечания

2023-01-10 13:49 UTC, avtorsky commented
- реализован createShortURLWebForm - дополнительный хэндлер создания короткой ссылки из веб-форм
- для createShortURL и createShortURLWebForm теперь дополнительно проверяется, что базовый URL на входе не только не пустой, но и содержит протокол и хост
- исключен слой абстракций services
- привёл в порядок наименования сущностей
- покрыл тестами дополнительную валидацию URL в createShortURLWebForm

2023-01-10 21:30 UTC, Barugoo commented on internal/server/server.go
> +	}
Кажется, что нам достаточно проверять, что `url.Parse` не вернуло ошибку - тогда мы будем уверены, что урл валидный:
```go
if _, err := url.Parse(baseURL); err != nil {
        ctx.String(http.StatusBadRequest, "Invalid URL host")
        return
}

2023-01-10 21:35 UTC, Barugoo commented on internal/storage/storage.go
> +	Insert(baseURL string) string
Метод `Insert` должен тоже возвращать ошибку, как я и писал в предыдущей итерации ревью. Мы делаем абстрактный интерфейс, а значит в качестве реализации там может быть и мапка в памяти, и работа с БД/файлом/удаленным сервером - в общем, все, что подразумевает ввод/вывод. 

А любой ввод-вывод может закончится ошибкой, которую мы явно захотим обработать на стороне вызывающего кода. Понятно, что с текущей реализацией возможность вернуть ошибку вряд ли будет задействована в `Insert` - мапка то всегда примет новый ключ. 

Но вот когда мы пересядем на БД/файл ситуация изменится и не очень хотелось бы менять код, который работает с этим интерфейсом при переходе к новой реализации - иначе в чем смысл?

2023-01-10 21:36 UTC, Barugoo commented on internal/server/server.go
> +	ctx.Writer.Write([]byte(shortURL))
Почему бы здесь не задействовать `ctx.String` как ты это делал выше?

2023-01-10 21:36 UTC, Barugoo commented on internal/server/server_test.go
> +			if tt.code == 307 {
Давай использовать константы для статусов:
```go
if tt.code == http.StatusTemporaryRedirect {

2023-01-10 21:38 UTC, Barugoo approved these changes
Работу принимаю, пожалуйста, поправь к следующему спринту замечание по интерфейсу `StorageDB`

2023-01-11 21:42 UTC, avtorsky commented
- внёс правки в интерфейс Storage
- поправил статусы согласно рекомендациям
- разобрался с указателями StorageDB и успешно прогнал statictest

2023-01-11 21:44 UTC, merged