feat(./internal/server): sprint2 iter8 gzip compression config
avtorsky/cuttlink pull request #8
Opened 2023-01-22 13:55 UTC by avtorsky

2023-01-24 20:47 UTC, Barugoo commented on internal/config/config.go
> +	FileStoragePath string `env:"FILE_STORAGE_PATH" envDefault:"kv_store.txt"`
>При отсутствии переменной окружения или при её пустом значении вернитесь к хранению сокращённых URL в памяти.

Лучше убрать значение по умолчанию так как в текущей конфигурации у нас сервер никогда не стартанет с хранилкой в памяти

2023-01-24 20:54 UTC, Barugoo commented on internal/server/server.go
> +	r.Use(decompressMiddleware())
У сигнатуры метода `r.Use` аргумент обозначен как variadic (`Use(middleware ...HandlerFunc) IRoutes`)  - тобишь можно передать все эти миддлвари одним вызовом, перечислив аргументы через запятую :
```go
r.Use(
    gin.Logger(),
    gin.Recovery(),
//...

2023-01-24 20:55 UTC, Barugoo commented on internal/server/server.go
> +			ctx.String(http.StatusInternalServerError, "Invalid payload")
Здесь и выше забыл `return`

2023-01-24 20:58 UTC, Barugoo commented on internal/server/server.go
> +	case "application/x-gzip":
Кажется, что код этого кейса полностью дублирует следующий кейс в свитче
В таких случаях можно делать так:
```go
switch headerContentType {
case "application/x-gzip", "text/plain; charset=utf-8":
    dataBytes, err := io.ReadAll(ctx.Request.Body)
    baseURL = strings.TrimSpace(string(dataBytes))
default:
    ctx.String(http.StatusInternalServerError, "Invalid Content-Type header")
    return
}

2023-01-24 21:00 UTC, Barugoo commented on internal/server/server.go
> +	switch headerContentType {
Будто бы здесь этот switch не нужен, этот код эквивалентен этому:
```go
if ctx.Request.Header.Get("Content-Type") != "application/json" {
    ctx.JSON(http.StatusInternalServerError, gin.H{
 	"message": "Invalid Content-Type header",
    })
    return
}
err := ctx.BindJSON(&payload)
//...

2023-01-24 21:03 UTC, Barugoo commented on internal/server/server.go
> +		if err != nil || payload.URL == "" {
Давай не будем мешать в одном условии проверку ошибки функции и валидацию результата, чтобы легче было читать:
```go
if err := ctx.BindJSON(&payload); err != nil {
    	ctx.JSON(http.StatusBadRequest, gin.H{
 		"message": "Invalid URL",
 	})
 	return
}
if _, err := url.Parse(payload.URL); err != nil {
        ctx.JSON(http.StatusBadRequest, gin.H{
 	        "message": "Invalid URL scheme",
        })
        return
}

2023-01-24 21:04 UTC, Barugoo commented on internal/server/server.go
> +	}
А нужно ли нам это так дотошно проверять? Кажется, более чем достаточно просто проверить что `payload.URL` переданный в `url.Parse` не приводит к ошибке

2023-01-24 21:08 UTC, Barugoo commented on internal/server/server.go
> +	key := s.storage.Insert(payload.URL)
Странно, что метод хранилки на вставку не возвращает ошибку. У нас же теперь там под капотом может происходить ввод-вывод (запись в файл), который всегда может вернуть ошибку

2023-01-24 21:08 UTC, Barugoo commented on internal/server/server.go
> +	result, _ := json.Marshal(shortURL)
Давай проверять здесь ошибку

2023-01-24 21:08 UTC, Barugoo commented on internal/server/server.go
> +	fmt.Println(string(result))
И уберем этот лог

2023-01-24 21:09 UTC, Barugoo commented on internal/storage/file.go
> +}
Хмм
А нужен ли нам этот интерфейс? Ну то есть да, он поможет нам мокать те места в коде, где мы вызываем методы хранилки файла. Но кажется будет правильнее и удобнее сделать общий интерфейс хранилки, и под него уже подгонять разные реализации:
Почитай тута раздел "Репозитории" https://habr.com/ru/company/domclick/blog/592087/

2023-01-24 21:13 UTC, Barugoo requested changes
Хорошо, но есть замечания
Жду доработок!

2023-01-29 09:33 UTC, avtorsky commented
- в конфиге сервера реализовал приоритет значений, полученных через ENV, перед значениями, задаваемыми посредством флагов
- проверил валидацию ссылки методом url.ParseRequestURI - не исключает обработку пустого хоста, по этой причине оставил во всех хэндлерах сдвоенную реализацию проверки схемы и хоста ссылки методами url.ParseRequestURI (через проверку ошибки) и url.Parse (через проверку значения)
- дополнительную сериализацию shortURL в хэндлере createShortURLJSON методом json.Marshal с выводом принта в лог оставил, добавив проверку ошибки, так как без неё не проходит shortenertest, несмотря на то, что хэндлер createShortURLJSON использует встроенный в gin сериализатор
- в случае ошибки конфигурации сервера реализовал проброс ошибки из вспомогательного пакета в основной
- внёс правки по комментариям code review

2023-01-31 11:04 UTC, Barugoo approved these changes
Отлично! Работу принимаю

2023-02-01 03:39 UTC, merged